Repository HumanCellAtlas/metadata-schema, pull requests merged in 2018-09, with the labels that each got.

#525 Name/title bug fix
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/module/ontology/cellular_component_ontology.json
  json_schema/module/ontology/microscopy_ontology.json
  json_schema/type/file/supplementary_file.json
  json_schema/versions.json
Labels: bug, done

#531 Draft of Metadata Style Guide
  docs/schema_style_guide.md
Labels: documentation

#434 [WIP] Added new metadata style guide
  docs/README.md
  docs/schema_style_guide.md
Labels: documentation

#534 Metadata Style Guide
  docs/schema_style_guide.md
Labels: documentation

#544 Documentation Review: release_process.md Part of #487 and #543
  docs/release_process.md
Labels: documentation

#549 Bug fix to organ_ontology by including embryo as allowed value
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/module/ontology/organ_ontology.json
  json_schema/versions.json
Labels: bug, content

#551 Release from integration to staging 2018-09-19
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  docs/release_process.md
  docs/schema_style_guide.md
  json_schema/module/ontology/organ_ontology.json
  json_schema/versions.json
Labels: release

#546 Documentation review: evolution.md
  docs/committers.md
  docs/evolution.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
Labels: documentation

#556 Bug fix: added project_core as required field to project. Fixes #554
  changelog.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/project/project.json
  json_schema/versions.json
Labels: bug

#559 Mf cell line pub fix issue557
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/biomaterial/cell_line.json
  json_schema/versions.json
Labels: content

#560 Add unknown to enum for strand field. Fixes #544.
  changelog.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/protocol/sequencing/library_preparation_protocol.json
  json_schema/versions.json
Labels: content

#545 Documentation review: rationale.md. Part of #487 and #543
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  docs/rationale.md
Labels: documentation

#547 Documentation review: structure.md Part of #487 and #543
  docs/structure.md
Labels: documentation

#558 Documentation review: committers.md. Part of #487 and #543
  docs/committers.md
Labels: documentation

#562 Documentation review: bug_report.md. Part of #487 and #543
  .github/ISSUE_TEMPLATE/bug_report.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
Labels: documentation

#565 Updated is_living friendly name
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/biomaterial/donor_organism.json
  json_schema/versions.json
Labels: content

#566 Changed organ_ontology restriction to UBERON:0000465
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/module/ontology/organ_ontology.json
  json_schema/versions.json
Labels: content

#568 Release from develop to integration 2018-09-25
  .github/ISSUE_TEMPLATE/bug_report.md
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  examples/bundles/public-beta/1M Immune Cells/links.json
  examples/bundles/public-beta/CD4+ cytotoxic T lymphocytes/links.json
  examples/bundles/public-beta/HPSI_human_cerebral_organoids/links.json
  examples/bundles/public-beta/Healthy and type 2 diabetes pancreas/links.json
  examples/bundles/public-beta/Mouse Melanoma/links.json
  examples/bundles/public-beta/Single cell transcriptome analysis of human pancreas/links.json
  examples/bundles/public-beta/Tissue stability/links.json
  json_schema/module/ontology/organ_ontology.json
  json_schema/type/biomaterial/donor_organism.json
  json_schema/versions.json
Labels: release

#569 Release from staging to production 2018-09-25
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  docs/release_process.md
  docs/schema_style_guide.md
  json_schema/module/ontology/organ_ontology.json
  json_schema/versions.json
Labels: release

#561 Documentation review: contributing.md Part of #487 and #543
  docs/contributing.md
Labels: documentation
