Repository HumanCellAtlas/metadata-schema, pull requests merged in 2018-08, with the labels that each got.

#465 Mf update committers doc
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/new_schema.md
  .github/ISSUE_TEMPLATE/schema_update.md
  docs/committers.md
  docs/contributing.md
  docs/release_process.md
Labels: documentation

#463 Biological sex shorten. Fixes #384
  changelog.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/biomaterial/donor_organism.json
  json_schema/versions.json
  schema_test_files/biomaterial/test_pass_donor_organism_0.json
Labels: content

#472 Fix friendly name for sequencing approach
  changelog.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/protocol/sequencing/sequencing_protocol.json
  json_schema/versions.json
Labels: bug, content

#473 paired ends to paired end issue #467
  changelog.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/protocol/sequencing/sequencing_protocol.json
  json_schema/versions.json
  schema_test_files/protocol/test_pass_sequencing_protocol.json
Labels: content

#425 [WIP] Added attribute for technical replicate ID
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/file/sequence_file.json
  json_schema/versions.json
Labels: content

#476 Add supplementary_links field for URLs. Fixes #438.
  changelog.md
  docs/jsonBrowser/type.md
  json_schema/type/project/project.json
  json_schema/versions.json
Labels: content

#479 [WIP] Release schemas from develop to master
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/new_schema.md
  .github/ISSUE_TEMPLATE/schema_update.md
  changelog.md
  docs/committers.md
  docs/contributing.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  docs/release_process.md
  infrastructure_testing_files/current/README.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.yaml
  json_schema/core/process/process_core.json
  json_schema/module/biomaterial/familial_relationship.json
  json_schema/type/biomaterial/donor_organism.json
  json_schema/type/file/sequence_file.json
  json_schema/type/project/project.json
  json_schema/type/protocol/sequencing/sequencing_protocol.json
  json_schema/versions.json
  schema_test_files/biomaterial/test_pass_donor_organism_0.json
  schema_test_files/protocol/test_pass_sequencing_protocol.json
Labels: content

#496 Bug fix to ethnicity_ontology
  changelog.md
  json_schema/module/ontology/ethnicity_ontology.json
  json_schema/versions.json
Labels: bug

#499 New SLO doc
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  docs/metadata_slo.md
Labels: documentation

#503 Updated DCP-wide integration test spreadsheet
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
Labels: infrastructure

#500 Add stem cell to cell line type enum. Fixes #498.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/biomaterial/cell_line.json
  json_schema/versions.json
Labels: content

#474 New culture_environment field. Fixes #234.
  changelog.md
  docs/jsonBrowser/module.md
  json_schema/module/biomaterial/growth_conditions.json
  json_schema/versions.json
Labels: content

#502 Simplified induced_pluripotent_cell_* names to ipsc_*. Fixes #481
  changelog.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/protocol/biomaterial_collection/ipsc_induction_protocol.json
  json_schema/versions.json
Labels: content

#507 Removed all bundle tests as they are no longer relevant
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  schema_test_files/biomaterial/test_fail_biomaterial_bundle.json
  schema_test_files/biomaterial/test_pass_biomaterial_bundle.json
  schema_test_files/file/test_pass_reference_bundle_0.json
  schema_test_files/process/test_pass_analysis_process.json
  schema_test_files/process/test_pass_process_bundle.json
  schema_test_files/process/test_pass_sequencing_process.json
  schema_test_files/project/test_pass_project_bundle.json
  src/json_examples_validate_against_schema.py
Labels: infrastructure, task

#509 New example analysis process
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  schema_test_files/process/test_pass_new_analysis_process.json
  src/json_examples_validate_against_schema.py
Labels: infrastructure

#512 Fixed bug causing ontology schema validation issue
  changelog.md
  json_schema/module/ontology/disease_ontology.json
  json_schema/module/ontology/ethnicity_ontology.json
  json_schema/module/ontology/organ_ontology.json
  json_schema/module/ontology/strain_ontology.json
  json_schema/versions.json
Labels: bug, content

#520 Updated integration test spreadsheet from integration to staging branch.
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
Labels: release, task
