Repository HumanCellAtlas/metadata-schema, pull requests merged in 2018-12, with the labels that each got.

#618 Cell line schema patch updates.
  changelog.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/biomaterial/cell_line.json
  json_schema/versions.json
Labels: content

#622 Cell suspension schema patch updates.
  changelog.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/biomaterial/cell_suspension.json
  json_schema/versions.json
Labels: content

#661 Release from integration to staging - 2018-12-06
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/module/protocol/imaging_target.json
  json_schema/versions.json
Labels: release

#657 Organoid patch updates
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/biomaterial/organoid.json
  json_schema/versions.json
Labels: content

#654 Specimen_from_organism patch updates.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/biomaterial/specimen_from_organism.json
  json_schema/versions.json
Labels: content

#663 Contact module patch updates.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/module/project/contact.json
  json_schema/versions.json
Labels: content

#651 Donor_organism patch updates.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/biomaterial/donor_organism.json
  json_schema/versions.json
Labels: content

#667 Changed molecule_ID to lower case. Fixes #666
  docs/jsonBrowser/module.md
  json_schema/module/protocol/target.json
  json_schema/update_log.csv
Labels: bug

#665 Release from develop to integration - 2018-12-07
  .gitignore
  .travis.yml
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/module/project/contact.json
  json_schema/module/protocol/channel.json
  json_schema/module/protocol/target.json
  json_schema/system/links.json
  json_schema/type/biomaterial/cell_line.json
  json_schema/type/biomaterial/cell_suspension.json
  json_schema/type/biomaterial/donor_organism.json
  json_schema/type/biomaterial/imaged_specimen.json
  json_schema/type/biomaterial/organoid.json
  json_schema/type/biomaterial/specimen_from_organism.json
  json_schema/type/file/sequence_file.json
  json_schema/type/protocol/imaging/imaging_protocol.json
  json_schema/type/protocol/sequencing/library_preparation_protocol.json
  json_schema/versions.json
  tests/README.md
  tests/package-lock.json
  tests/package.json
  tests/schema.test.js
  tests/schema_test_files/README.md
  tests/schema_test_files/biomaterial/test_fail_biomaterial_bundle.json~
  tests/schema_test_files/biomaterial/test_fail_specimen_0.json
  tests/schema_test_files/biomaterial/test_fail_specimen_0.json~
  tests/schema_test_files/biomaterial/test_pass_biomaterial_bundle.json~
  tests/schema_test_files/biomaterial/test_pass_donor_organism_0.json
  tests/schema_test_files/biomaterial/test_pass_specimen_0.json
  tests/schema_test_files/biomaterial/test_pass_specimen_0.json~
  tests/schema_test_files/conf.json
  tests/schema_test_files/process/test_pass_analysis_process.json
  tests/schema_test_files/process/test_pass_new_analysis_process.json
  tests/schema_test_files/project/test_fail_project_0.json
  tests/schema_test_files/project/test_pass_project_0.json
  tests/schema_test_files/protocol/test_pass_sequencing_protocol.json
Labels: release

#351 Add licensing information to project
  changelog.md
  json_schema/system/license.json
  json_schema/versions.json
Labels: content

#673 Sequence file patch updates.
  changelog.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/file/sequence_file.json
  json_schema/versions.json
Labels: content

#689 Biomaterial collection protocols patch updates.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/protocol/biomaterial_collection/aggregate_generation_protocol.json
  json_schema/type/protocol/biomaterial_collection/collection_protocol.json
  json_schema/type/protocol/biomaterial_collection/differentiation_protocol.json
  json_schema/type/protocol/biomaterial_collection/dissociation_protocol.json
  json_schema/type/protocol/biomaterial_collection/enrichment_protocol.json
  json_schema/type/protocol/biomaterial_collection/ipsc_induction_protocol.json
  json_schema/versions.json
Labels: content

#696 Release from staging to production - 2018-12-18
  .gitignore
  .travis.yml
  changelog.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/module/project/contact.json
  json_schema/module/protocol/channel.json
  json_schema/module/protocol/target.json
  json_schema/system/links.json
  json_schema/type/biomaterial/cell_line.json
  json_schema/type/biomaterial/cell_suspension.json
  json_schema/type/biomaterial/donor_organism.json
  json_schema/type/biomaterial/imaged_specimen.json
  json_schema/type/biomaterial/organoid.json
  json_schema/type/biomaterial/specimen_from_organism.json
  json_schema/type/file/sequence_file.json
  json_schema/type/protocol/imaging/imaging_protocol.json
  json_schema/type/protocol/sequencing/library_preparation_protocol.json
  json_schema/versions.json
  tests/README.md
  tests/package-lock.json
  tests/package.json
  tests/schema.test.js
  tests/schema_test_files/README.md
  tests/schema_test_files/biomaterial/test_fail_biomaterial_bundle.json~
  tests/schema_test_files/biomaterial/test_fail_specimen_0.json
  tests/schema_test_files/biomaterial/test_fail_specimen_0.json~
  tests/schema_test_files/biomaterial/test_pass_biomaterial_bundle.json~
  tests/schema_test_files/biomaterial/test_pass_donor_organism_0.json
  tests/schema_test_files/biomaterial/test_pass_specimen_0.json
  tests/schema_test_files/biomaterial/test_pass_specimen_0.json~
  tests/schema_test_files/conf.json
  tests/schema_test_files/process/test_pass_analysis_process.json
  tests/schema_test_files/process/test_pass_new_analysis_process.json
  tests/schema_test_files/project/test_fail_project_0.json
  tests/schema_test_files/project/test_pass_project_0.json
  tests/schema_test_files/protocol/test_pass_sequencing_protocol.json
Labels: release

#660 Update Style guide examples
  docs/schema_style_guide.md
Labels: documentation
