Repository HumanCellAtlas/metadata-schema, pull requests merged in 2018-10, with the labels that each got.

#573 Release from develop to integration 2018-10-09
  docs/contributing.md
Labels: release

#574 Release from integration to staging 2018-10-09
  docs/contributing.md
Labels: release

#575 Release from staging to production 2018-10-09
  docs/contributing.md
Labels: release

#581 New repo task issue template
  .github/ISSUE_TEMPLATE/repo_task.md
Labels: infrastructure

#580 Fixed committers doc. Fixes #578.
  docs/committers.md
Labels: documentation

#582 Added pancreas6decades spreadsheet
  infrastructure_testing_files/current/dcp_scale_test_pancreas6decades.xlsx
Labels: infrastructure

#583 Release from integration to develop - 2018-10-11
  .github/ISSUE_TEMPLATE/repo_task.md
  docs/committers.md
  infrastructure_testing_files/current/dcp_scale_test_pancreas6decades.xlsx
Labels: release

#577 Remove protocol_type field from imaging_protocol.json Fixes issue #572
  changelog.md
  json_schema/type/protocol/imaging/imaging_protocol.json
  json_schema/versions.json
Labels: bug, content

#585 Update 10x fastq file names in test metadata spreadsheet
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
Labels: infrastructure

#586 Release from develop to integration - 2018-10-11
  changelog.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  json_schema/type/protocol/imaging/imaging_protocol.json
  json_schema/versions.json
Labels: release

#588 Changed Project label to Project shortname
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
Labels: infrastructure

#589 Release develop to integration - 2018-10-12
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
Labels: release

#591 Update schema readme
  json_schema/README.md
Labels: documentation

#593 Updated paired_end description
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/protocol/sequencing/sequencing_protocol.json
  json_schema/versions.json
Labels: content

#597 Release from develop to integration - 2018-10-17
  changelog.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/README.md
  json_schema/type/protocol/sequencing/sequencing_protocol.json
  json_schema/versions.json
Labels: release

#599 Release from integration to staging - 2018-10-17
  .github/ISSUE_TEMPLATE/repo_task.md
  changelog.md
  docs/committers.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  infrastructure_testing_files/current/dcp_scale_test_pancreas6decades.xlsx
  json_schema/README.md
  json_schema/type/protocol/imaging/imaging_protocol.json
  json_schema/type/protocol/sequencing/sequencing_protocol.json
  json_schema/versions.json
Labels: release

#598 Add Zenhub runbook document
  docs/Zenhub_runbook.md
Labels: documentation

#600 Release from staging to production - 2018-10-23
  .github/ISSUE_TEMPLATE/repo_task.md
  changelog.md
  docs/committers.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  infrastructure_testing_files/current/dcp_scale_test_pancreas6decades.xlsx
  json_schema/README.md
  json_schema/type/protocol/imaging/imaging_protocol.json
  json_schema/type/protocol/sequencing/sequencing_protocol.json
  json_schema/versions.json
Labels: release

#603 Release from integration to staging - 2018-10-25
  docs/Zenhub_runbook.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
Labels: release

#604 Release from staging to master - 2018-10-25.
  docs/Zenhub_runbook.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
Labels: release
