Repository HumanCellAtlas/metadata-schema, pull requests merged in 2019-04, with the labels that each got.

#912 Release from develop to integration - 2019-04-01
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  docs/schema_style_guide.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_optimus_10X_bundle.xlsx
  json_schema/module/protocol/channel.json
  json_schema/type/project/project.json
  json_schema/versions.json
Labels: release

#908 Added new contributor role ontology schema. Fixes #893.
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/module/ontology/contributor_role_ontology.json
  json_schema/update_log.csv
  json_schema/versions.json
Labels: content

#913 Release from staging to production - 2019-04-02
  .github/pull_request_template.md
  README.md
  changelog.md
  docs/committers.md
  docs/images/project_scenario.jpg
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  docs/rationale.md
  docs/release_process.md
  docs/structure.md
  docs/test_plan.md
  examples/sample_property_migrations.json
  examples/update_log_example.csv
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
  json_schema/module/biomaterial/medical_history.json
  json_schema/module/biomaterial/preservation_storage.json
  json_schema/module/biomaterial/state_of_specimen.json
  json_schema/module/ontology/ethnicity_ontology.json
  json_schema/module/process/sequencing/insdc_experiment.json
  json_schema/module/process/sequencing/plate_based_sequencing.json
  json_schema/module/project/contact.json
  json_schema/module/protocol/channel.json
  json_schema/module/protocol/target.json
  json_schema/property_migrations.json
  json_schema/type/biomaterial/cell_line.json
  json_schema/type/biomaterial/specimen_from_organism.json
  json_schema/type/file/image_file.json
  json_schema/type/file/sequence_file.json
  json_schema/type/process/analysis/analysis_process.json
  json_schema/type/protocol/biomaterial_collection/collection_protocol.json
  json_schema/type/protocol/biomaterial_collection/dissociation_protocol.json
  json_schema/type/protocol/imaging/imaging_preparation_protocol.json
  json_schema/type/protocol/sequencing/library_preparation_protocol.json
  json_schema/type/protocol/sequencing/sequencing_protocol.json
  json_schema/versions.json
  src/json_doc_migrations.py
  src/migration_test_donor1.json
  src/migration_test_donor2.json
  src/migration_test_specimen1.json
  src/schema_linter.py
  tests/schema_test_files/biomaterial/test_fail_specimen_0.json
  tests/schema_test_files/biomaterial/test_pass_specimen_0.json
  tests/schema_test_files/process/test_pass_analysis_process.json
  tests/schema_test_files/process/test_pass_new_analysis_process.json
Labels: release

#920 ESV preservation_storage.json Fixes #916
  changelog.md
  docs/jsonBrowser/module.md
  json_schema/module/biomaterial/preservation_storage.json
  json_schema/versions.json
Labels: content

#914 Release from integration to staging - 2019-04-03
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  docs/schema_style_guide.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_optimus_10X_bundle.xlsx
  json_schema/module/protocol/channel.json
  json_schema/type/project/project.json
  json_schema/versions.json
Labels: release

#936 Changed cell_line_type to type. Fixes #935
  changelog.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/property_migrations.json
  json_schema/type/biomaterial/cell_line.json
  json_schema/versions.json
Labels: content

#933 Changed publication_title to title and publication_url to url. Fixes #928.
  changelog.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  json_schema/module/project/publication.json
  json_schema/versions.json
Labels: content

#940 Added property migration info for PR #933.
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/property_migrations.json
Labels: content

#932 Change biosd_biomaterial to biosamples_accession, insdc_biomaterial to insdc_sample_accession. Fixes #929
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/core/biomaterial/biomaterial_core.json
  json_schema/property_migrations.json
  json_schema/versions.json
  src/schemas_are_valid_json.py
Labels: content

#944 Changed differentiation_method to method. Fixes #924.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/property_migrations.json
  json_schema/type/protocol/biomaterial_collection/differentiation_protocol.json
  json_schema/update_log.csv
  json_schema/versions.json
Labels: content

#939 Release from staging to production - 2019-04-09
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  docs/schema_style_guide.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_optimus_10X_bundle.xlsx
  json_schema/module/protocol/channel.json
  json_schema/type/project/project.json
  json_schema/versions.json
Labels: release

#943 Enrichment protocol update. Fixes #925
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/property_migrations.json
  json_schema/type/protocol/biomaterial_collection/enrichment_protocol.json
  json_schema/update_log.csv
  json_schema/versions.json
Labels: content

#937 Changed process_location to location, operator to operators. Fixes #930.
  changelog.md
  docs/jsonBrowser/core.md
  json_schema/core/process/process_core.json
  json_schema/property_migrations.json
  json_schema/versions.json
Labels: content

#886 Probe module to replace target module. Fixes Issue#813.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/module/protocol/probe.json
  json_schema/versions.json
Labels: content, imaging

#941 Updated 4 fields in ipsc_induction_protocol. Fixes #926.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/property_migrations.json
  json_schema/type/protocol/biomaterial_collection/ipsc_induction_protocol.json
  json_schema/versions.json
Labels: content

#938 Added optional timecourse field to cell line. Fixes #917.
  changelog.md
  docs/jsonBrowser/type.md
  json_schema/type/biomaterial/cell_line.json
  json_schema/versions.json
Labels: content

#942 Changed selected_cell_type to selected_cell_types. Fixes #923.
  changelog.md
  docs/jsonBrowser/type.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_optimus_10X_bundle.xlsx
  json_schema/property_migrations.json
  json_schema/type/biomaterial/cell_suspension.json
  json_schema/versions.json
Labels: content

#952 Added HDBR_accession to biomaterial_core. Fixes Issue945.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/core/biomaterial/biomaterial_core.json
  json_schema/versions.json
Labels: content

#954 Updated description, guidelines and example for gestational_age. Fixes #911.
  changelog.md
  docs/jsonBrowser/type.md
  json_schema/type/biomaterial/donor_organism.json
  json_schema/versions.json
Labels: bug, content

#958 Changed file_format to format. Fixes #375.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_optimus_10X_bundle.xlsx
  json_schema/core/file/file_core.json
  json_schema/property_migrations.json
  json_schema/versions.json
  src/release_prepare.py
Labels: content

#956 Changed contact_name to name. Fixes #927.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_optimus_10X_bundle.xlsx
  json_schema/module/project/contact.json
  json_schema/property_migrations.json
  json_schema/versions.json
  tests/schema_test_files/project/test_fail_project_0.json
  tests/schema_test_files/project/test_pass_project_0.json
Labels: content

#960 Changed protocol_type/process_type properties to type. Fixes #931.
  changelog.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/property_migrations.json
  json_schema/type/process/analysis/analysis_process.json
  json_schema/type/process/process.json
  json_schema/type/protocol/analysis/analysis_protocol.json
  json_schema/type/protocol/protocol.json
  json_schema/versions.json
  tests/schema_test_files/process/test_pass_analysis_process.json
  tests/schema_test_files/process/test_pass_new_analysis_process.json
Labels: content

#968 Added description, example, user-friendly name, and guidelines to all definition fields. Fixes #955.
  json_schema/type/process/analysis/analysis_process.json
  json_schema/update_log.csv
Labels: content

#972 Changed date recognition on 4 schemas. Fixes #966
  changelog.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/type.md
  json_schema/module/biomaterial/death.json
  json_schema/module/process/purchased_reagents.json
  json_schema/type/biomaterial/cell_line.json
  json_schema/type/biomaterial/specimen_from_organism.json
  json_schema/versions.json
Labels: content

#947 Release from develop to integration - 2019-05-02
  changelog.md
  docs/committers.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_optimus_10X_bundle.xlsx
  json_schema/core/biomaterial/biomaterial_core.json
  json_schema/core/file/file_core.json
  json_schema/core/process/process_core.json
  json_schema/module/biomaterial/death.json
  json_schema/module/biomaterial/preservation_storage.json
  json_schema/module/ontology/contributor_role_ontology.json
  json_schema/module/process/purchased_reagents.json
  json_schema/module/project/contact.json
  json_schema/module/project/publication.json
  json_schema/module/protocol/probe.json
  json_schema/property_migrations.json
  json_schema/type/biomaterial/cell_line.json
  json_schema/type/biomaterial/cell_suspension.json
  json_schema/type/biomaterial/donor_organism.json
  json_schema/type/biomaterial/specimen_from_organism.json
  json_schema/type/process/analysis/analysis_process.json
  json_schema/type/process/process.json
  json_schema/type/protocol/analysis/analysis_protocol.json
  json_schema/type/protocol/biomaterial_collection/differentiation_protocol.json
  json_schema/type/protocol/biomaterial_collection/enrichment_protocol.json
  json_schema/type/protocol/biomaterial_collection/ipsc_induction_protocol.json
  json_schema/type/protocol/protocol.json
  json_schema/versions.json
  src/release_prepare.py
  src/schemas_are_valid_json.py
  src/version_update.py
  tests/schema_test_files/process/test_pass_analysis_process.json
  tests/schema_test_files/process/test_pass_new_analysis_process.json
  tests/schema_test_files/project/test_fail_project_0.json
  tests/schema_test_files/project/test_pass_project_0.json
Labels: release
