Repository HumanCellAtlas/metadata-schema, pull requests merged in 2019-06, with the labels that each got.

#1010 Added user friendly names to several fields in provenance. Fixes #989
  changelog.md
  json_schema/system/provenance.json
  json_schema/versions.json
Labels: content

#1011 Add more checks to linter. Fixes #959 and #890.
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  src/schema_linter.py
Labels: infrastructure

#1018 Add pull approve functionality to repo. Fixes #866.
  .pullapprove.yml
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
Labels: infrastructure

#1020 Release from develop to integration - 2019-06-05
  .githooks/pre-commit
  .pullapprove.yml
  .travis.yml
  README.md
  changelog.md
  docs/images/entities.graffle
  docs/images/entities.png
  docs/images/project_scenario.graffle
  docs/images/project_scenario.png
  docs/images/unit_of_hierarchy.graffle
  docs/images/unit_of_hierarchy.jpg
  docs/images/unit_of_hierarchy.png
  docs/images/unit_scenarios.graffle
  docs/images/unit_scenarios.png
  docs/images/wrapper_process.graffle
  docs/images/wrapper_process.png
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  docs/structure.md
  json_schema/module/biomaterial/death.json
  json_schema/module/project/contact.json
  json_schema/module/protocol/channel.json
  json_schema/system/provenance.json
  json_schema/type/biomaterial/donor_organism.json
  json_schema/type/biomaterial/organoid.json
  json_schema/type/protocol/biomaterial_collection/ipsc_induction_protocol.json
  json_schema/type/protocol/imaging/imaging_protocol.json
  json_schema/type/protocol/sequencing/sequencing_protocol.json
  json_schema/versions.json
  src/schema_linter.py
Labels: release

#1021 Schema linter now checking for valid ontologies and parent classes. Fixes #1012
  .githooks/pre-commit
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  src/schema_linter.py
Labels: infrastructure

#1019 Switching to pre-commit package. Fixes #1006
  .pre-commit-config.yaml
  .pre-commit-hooks.yaml
  README.md
  src/add_docs.sh
  src/human_readable_json.py
  src/schema_linter.py
Labels: infrastructure

#752 Add required file content description field. Fixes #542.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  json_schema/core/file/file_core.json
  json_schema/module/ontology/file_content_ontology.json
  json_schema/versions.json
  tests/schema_test_files/process/test_pass_analysis_process.json
Labels: content

#1026 Fixed small bug with schema linter. Fixes #1024
  src/schema_linter.py
Labels: infrastructure

#1034 Added code to check for schema description on line 77. Fixes #1031
  src/schema_linter.py
Labels: infrastructure

#1028 Fixed travis notifications and pre-commit hooks. Fixes #1025
  .githooks/generate_md_docs.sh
  .pre-commit-config.yaml
  .travis.yml
  src/add_docs.sh
Labels: bug, infrastructure

#1039 Release from integration to staging - 2019-06-12
  .githooks/pre-commit
  .pullapprove.yml
  .travis.yml
  README.md
  changelog.md
  docs/images/entities.graffle
  docs/images/entities.png
  docs/images/project_scenario.graffle
  docs/images/project_scenario.png
  docs/images/unit_of_hierarchy.graffle
  docs/images/unit_of_hierarchy.jpg
  docs/images/unit_of_hierarchy.png
  docs/images/unit_scenarios.graffle
  docs/images/unit_scenarios.png
  docs/images/wrapper_process.graffle
  docs/images/wrapper_process.png
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  docs/structure.md
  json_schema/module/biomaterial/death.json
  json_schema/module/project/contact.json
  json_schema/module/protocol/channel.json
  json_schema/system/provenance.json
  json_schema/type/biomaterial/donor_organism.json
  json_schema/type/biomaterial/organoid.json
  json_schema/type/protocol/biomaterial_collection/ipsc_induction_protocol.json
  json_schema/type/protocol/imaging/imaging_protocol.json
  json_schema/type/protocol/sequencing/sequencing_protocol.json
  json_schema/versions.json
  src/schema_linter.py
Labels: release

#1036 Updated integration test spreadsheets. Fixes #1033.
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_optimus_10X_bundle.xlsx
Labels: infrastructure

#1040 Release from develop to integration - 2019-06-14
  .githooks/generate_md_docs.sh
  .githooks/pre-commit
  .pre-commit-config.yaml
  .pre-commit-hooks.yaml
  .travis.yml
  README.md
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_optimus_10X_bundle.xlsx
  json_schema/core/file/file_core.json
  json_schema/module/ontology/file_content_ontology.json
  json_schema/module/ontology/file_format_ontology.json
  json_schema/versions.json
  src/human_readable_json.py
  src/schema_linter.py
  tests/schema_test_files/process/test_pass_analysis_process.json
Labels: release

#1046 Release from integration to staging - 2019-06-26
  .githooks/generate_md_docs.sh
  .githooks/pre-commit
  .pre-commit-config.yaml
  .pre-commit-hooks.yaml
  .travis.yml
  README.md
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_optimus_10X_bundle.xlsx
  json_schema/core/file/file_core.json
  json_schema/module/ontology/file_content_ontology.json
  json_schema/module/ontology/file_format_ontology.json
  json_schema/versions.json
  src/human_readable_json.py
  src/schema_linter.py
  tests/schema_test_files/process/test_pass_analysis_process.json
Labels: release

#1050 [Snyk] Fix for 1 vulnerable dependencies
  tests/package-lock.json
  tests/package.json
Labels: Security

#1051 [Snyk] Fix for 1 vulnerable dependencies
  tests/package-lock.json
  tests/package.json
Labels: Security

#1052 [Snyk] Fix for 1 vulnerable dependencies
  tests/package-lock.json
  tests/package.json
Labels: Security

#1038 Fixed file_content_ontology module graph_restriction and examples. Fixes #1037
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/module/ontology/file_content_ontology.json
  json_schema/versions.json
Labels: content
