Repository HumanCellAtlas/metadata-schema, pull requests merged in 2019-03, with the labels that each got.

#853 Updated linter to exclude top-level JSON files.
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  src/schema_linter.py
Labels: infrastructure

#840 Remove outputs field from analysis_process schema. Fixes #664.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/process/analysis/analysis_process.json
  json_schema/versions.json
  tests/schema_test_files/process/test_pass_analysis_process.json
  tests/schema_test_files/process/test_pass_new_analysis_process.json
Labels: content

#836 Change nucleic_acid_source field to be required. Fixes #824.
  changelog.md
  json_schema/type/protocol/sequencing/library_preparation_protocol.json
  json_schema/versions.json
Labels: content

#854 Update integration test spreadsheets
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
Labels: content

#857 Release from integration to staging - 2019-03-05
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
Labels: release

#555 first pass at a test plan for the metadata schema
  docs/test_plan.md
Labels: documentation, help wanted

#767 Change organ_part to an array. Fixes #648.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
  json_schema/type/biomaterial/specimen_from_organism.json
  json_schema/versions.json
  tests/schema_test_files/biomaterial/test_fail_specimen_0.json
  tests/schema_test_files/biomaterial/test_pass_specimen_0.json
Labels: content

#882 Release from staging to production - 2019-03-12
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
Labels: release

#881 Added second example to test_results. Fixes #846.
  changelog.md
  docs/jsonBrowser/module.md
  json_schema/module/biomaterial/medical_history.json
  json_schema/versions.json
Labels: content

#875 Release from develop to integration - 14-03-2019
  .github/pull_request_template.md
  README.md
  changelog.md
  docs/committers.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  docs/release_process.md
  docs/test_plan.md
  examples/sample_property_migrations.json
  examples/update_log_example.csv
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
  json_schema/module/biomaterial/medical_history.json
  json_schema/module/biomaterial/preservation_storage.json
  json_schema/module/biomaterial/state_of_specimen.json
  json_schema/module/ontology/ethnicity_ontology.json
  json_schema/module/process/sequencing/insdc_experiment.json
  json_schema/module/process/sequencing/plate_based_sequencing.json
  json_schema/module/project/contact.json
  json_schema/module/protocol/channel.json
  json_schema/module/protocol/target.json
  json_schema/property_migrations.json
  json_schema/type/biomaterial/cell_line.json
  json_schema/type/biomaterial/specimen_from_organism.json
  json_schema/type/file/image_file.json
  json_schema/type/file/sequence_file.json
  json_schema/type/process/analysis/analysis_process.json
  json_schema/type/protocol/biomaterial_collection/collection_protocol.json
  json_schema/type/protocol/biomaterial_collection/dissociation_protocol.json
  json_schema/type/protocol/imaging/imaging_preparation_protocol.json
  json_schema/type/protocol/sequencing/library_preparation_protocol.json
  json_schema/type/protocol/sequencing/sequencing_protocol.json
  json_schema/versions.json
  src/json_doc_migrations.py
  src/migration_test_donor1.json
  src/migration_test_donor2.json
  src/migration_test_specimen1.json
  src/schema_linter.py
  tests/schema_test_files/biomaterial/test_fail_specimen_0.json
  tests/schema_test_files/biomaterial/test_pass_specimen_0.json
  tests/schema_test_files/process/test_pass_analysis_process.json
  tests/schema_test_files/process/test_pass_new_analysis_process.json
Labels: release

#887 Release from develop to integration - changelog fix
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
Labels: release

#888 Integration test spreadsheet fixes.
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
Labels: release

#843 Well and plate ID to well and plate label. Fixes #837.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
  json_schema/module/process/sequencing/plate_based_sequencing.json
  json_schema/versions.json
Labels: content

#896 Release from integration to staging - 2019-03-20
  .github/pull_request_template.md
  README.md
  changelog.md
  docs/committers.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  docs/release_process.md
  docs/test_plan.md
  examples/sample_property_migrations.json
  examples/update_log_example.csv
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
  json_schema/module/biomaterial/medical_history.json
  json_schema/module/biomaterial/preservation_storage.json
  json_schema/module/biomaterial/state_of_specimen.json
  json_schema/module/ontology/ethnicity_ontology.json
  json_schema/module/process/sequencing/insdc_experiment.json
  json_schema/module/process/sequencing/plate_based_sequencing.json
  json_schema/module/project/contact.json
  json_schema/module/protocol/channel.json
  json_schema/module/protocol/target.json
  json_schema/property_migrations.json
  json_schema/type/biomaterial/cell_line.json
  json_schema/type/biomaterial/specimen_from_organism.json
  json_schema/type/file/image_file.json
  json_schema/type/file/sequence_file.json
  json_schema/type/process/analysis/analysis_process.json
  json_schema/type/protocol/biomaterial_collection/collection_protocol.json
  json_schema/type/protocol/biomaterial_collection/dissociation_protocol.json
  json_schema/type/protocol/imaging/imaging_preparation_protocol.json
  json_schema/type/protocol/sequencing/library_preparation_protocol.json
  json_schema/type/protocol/sequencing/sequencing_protocol.json
  json_schema/versions.json
  src/json_doc_migrations.py
  src/migration_test_donor1.json
  src/migration_test_donor2.json
  src/migration_test_specimen1.json
  src/schema_linter.py
  tests/schema_test_files/biomaterial/test_fail_specimen_0.json
  tests/schema_test_files/biomaterial/test_pass_specimen_0.json
  tests/schema_test_files/process/test_pass_analysis_process.json
  tests/schema_test_files/process/test_pass_new_analysis_process.json
Labels: release

#898 Updates to structure, rationale, and release process docs.
  docs/images/project_scenario.jpg
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  docs/rationale.md
  docs/release_process.md
  docs/structure.md
Labels: documentation

#901 Release from develop to integration
  changelog.md
  docs/images/project_scenario.jpg
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/rationale.md
  docs/release_process.md
  docs/structure.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
  json_schema/module/process/sequencing/plate_based_sequencing.json
  json_schema/versions.json
Labels: release

#839 Describe use of ID fields in Style Guide. Fixes #838.
  docs/schema_style_guide.md
Labels: documentation

#895 Added optional biostudies_accesssion field. Fixes #852.
  changelog.md
  docs/jsonBrowser/type.md
  json_schema/type/project/project.json
  json_schema/versions.json
Labels: content

#909 Release from integration to staging - 2019-03-27
  changelog.md
  docs/images/project_scenario.jpg
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  docs/rationale.md
  docs/release_process.md
  docs/structure.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
  json_schema/module/process/sequencing/plate_based_sequencing.json
  json_schema/property_migrations.json
  json_schema/versions.json
Labels: release

#879 Changed filter_range example in channel.json. Fixes Issue878
  changelog.md
  json_schema/module/protocol/channel.json
  json_schema/versions.json
Labels: content, imaging
