Repository HumanCellAtlas/metadata-schema, pull requests merged in 2019-08, with the labels that each got.

#1096 Hotfix Release from Develop to Integration - 2019-08-14
  changelog.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/type.md
  docs/snyk_security_updates.md
  json_schema/module/ontology/biological_macromolecule_ontology.json
  json_schema/module/ontology/cell_cycle_ontology.json
  json_schema/module/ontology/cell_type_ontology.json
  json_schema/module/ontology/cellular_component_ontology.json
  json_schema/module/ontology/development_stage_ontology.json
  json_schema/module/ontology/disease_ontology.json
  json_schema/module/ontology/enrichment_ontology.json
  json_schema/module/ontology/ethnicity_ontology.json
  json_schema/module/ontology/instrument_ontology.json
  json_schema/module/ontology/length_unit_ontology.json
  json_schema/module/ontology/library_amplification_ontology.json
  json_schema/module/ontology/library_construction_ontology.json
  json_schema/module/ontology/mass_unit_ontology.json
  json_schema/module/ontology/microscopy_ontology.json
  json_schema/module/ontology/organ_part_ontology.json
  json_schema/module/ontology/process_type_ontology.json
  json_schema/module/ontology/protocol_type_ontology.json
  json_schema/module/ontology/sequencing_ontology.json
  json_schema/module/ontology/species_ontology.json
  json_schema/module/ontology/strain_ontology.json
  json_schema/module/ontology/time_unit_ontology.json
  json_schema/system/provenance.json
  json_schema/type/process/analysis/analysis_process.json
  json_schema/type/protocol/imaging/imaging_preparation_protocol.json
  json_schema/type/protocol/imaging/imaging_protocol.json
  json_schema/versions.json
  src/README.md
  src/human_readable_json.py
  src/json_doc_migrations.py
  src/migration_test_donor1.json
  src/migration_test_donor2.json
  src/migration_test_specimen1.json
  src/release_prepare.py
  src/version_update.py
  tests/package-lock.json
Labels: release

#1097 Release from integration to staging - 2019-08-14
  changelog.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/type.md
  docs/snyk_security_updates.md
  json_schema/module/ontology/biological_macromolecule_ontology.json
  json_schema/module/ontology/cell_cycle_ontology.json
  json_schema/module/ontology/cell_type_ontology.json
  json_schema/module/ontology/cellular_component_ontology.json
  json_schema/module/ontology/development_stage_ontology.json
  json_schema/module/ontology/disease_ontology.json
  json_schema/module/ontology/enrichment_ontology.json
  json_schema/module/ontology/ethnicity_ontology.json
  json_schema/module/ontology/instrument_ontology.json
  json_schema/module/ontology/length_unit_ontology.json
  json_schema/module/ontology/library_amplification_ontology.json
  json_schema/module/ontology/library_construction_ontology.json
  json_schema/module/ontology/mass_unit_ontology.json
  json_schema/module/ontology/microscopy_ontology.json
  json_schema/module/ontology/organ_part_ontology.json
  json_schema/module/ontology/process_type_ontology.json
  json_schema/module/ontology/protocol_type_ontology.json
  json_schema/module/ontology/sequencing_ontology.json
  json_schema/module/ontology/species_ontology.json
  json_schema/module/ontology/strain_ontology.json
  json_schema/module/ontology/time_unit_ontology.json
  json_schema/system/provenance.json
  json_schema/type/process/analysis/analysis_process.json
  json_schema/type/protocol/imaging/imaging_preparation_protocol.json
  json_schema/type/protocol/imaging/imaging_protocol.json
  json_schema/versions.json
  src/README.md
  src/human_readable_json.py
  src/json_doc_migrations.py
  src/migration_test_donor1.json
  src/migration_test_donor2.json
  src/migration_test_specimen1.json
  src/release_prepare.py
  src/version_update.py
  tests/package-lock.json
Labels: release

#1099 Release from staging to production - 2019-08-20
  changelog.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/type.md
  docs/snyk_security_updates.md
  json_schema/module/ontology/biological_macromolecule_ontology.json
  json_schema/module/ontology/cell_cycle_ontology.json
  json_schema/module/ontology/cell_type_ontology.json
  json_schema/module/ontology/cellular_component_ontology.json
  json_schema/module/ontology/development_stage_ontology.json
  json_schema/module/ontology/disease_ontology.json
  json_schema/module/ontology/enrichment_ontology.json
  json_schema/module/ontology/ethnicity_ontology.json
  json_schema/module/ontology/instrument_ontology.json
  json_schema/module/ontology/length_unit_ontology.json
  json_schema/module/ontology/library_amplification_ontology.json
  json_schema/module/ontology/library_construction_ontology.json
  json_schema/module/ontology/mass_unit_ontology.json
  json_schema/module/ontology/microscopy_ontology.json
  json_schema/module/ontology/organ_part_ontology.json
  json_schema/module/ontology/process_type_ontology.json
  json_schema/module/ontology/protocol_type_ontology.json
  json_schema/module/ontology/sequencing_ontology.json
  json_schema/module/ontology/species_ontology.json
  json_schema/module/ontology/strain_ontology.json
  json_schema/module/ontology/time_unit_ontology.json
  json_schema/system/provenance.json
  json_schema/type/process/analysis/analysis_process.json
  json_schema/type/protocol/imaging/imaging_preparation_protocol.json
  json_schema/type/protocol/imaging/imaging_protocol.json
  json_schema/versions.json
  src/README.md
  src/human_readable_json.py
  src/json_doc_migrations.py
  src/migration_test_donor1.json
  src/migration_test_donor2.json
  src/migration_test_specimen1.json
  src/release_prepare.py
  src/version_update.py
  tests/package-lock.json
Labels: release

#1110 [Snyk - Integration] Fix for 1 vulnerable dependencies
  tests/.snyk
  tests/package-lock.json
  tests/package.json
Labels: Security

#1111 [Snyk - staging] Fix for 1 vulnerable dependencies
  tests/.snyk
  tests/package-lock.json
  tests/package.json
Labels: Security

#1112 [Snyk - Prod] Fix for 1 vulnerable dependencies
  tests/.snyk
  tests/package-lock.json
  tests/package.json
Labels: Security

#1108 Fixed regex pattern matchings in Biomaterial_core. Fixes #1090
  changelog.md
  json_schema/core/biomaterial/biomaterial_core.json
  json_schema/versions.json
Labels: content

#1117 Release from develop to integration - 2019-08-30
  changelog.md
  json_schema/core/biomaterial/biomaterial_core.json
  json_schema/versions.json
Labels: release
