Repository HumanCellAtlas/metadata-schema, pull requests merged in 2019-07, with the labels that each got.

#1058 Added when primary release should happen. Fixes #1057.
  docs/release_process.md
Labels: documentation

#1056 Release from staging to production - 2019-07-02
  .githooks/generate_md_docs.sh
  .githooks/pre-commit
  .pre-commit-config.yaml
  .pre-commit-hooks.yaml
  .pullapprove.yml
  .travis.yml
  README.md
  changelog.md
  docs/images/entities.graffle
  docs/images/entities.png
  docs/images/project_scenario.graffle
  docs/images/project_scenario.png
  docs/images/unit_of_hierarchy.graffle
  docs/images/unit_of_hierarchy.jpg
  docs/images/unit_of_hierarchy.png
  docs/images/unit_scenarios.graffle
  docs/images/unit_scenarios.png
  docs/images/wrapper_process.graffle
  docs/images/wrapper_process.png
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  docs/structure.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_optimus_10X_bundle.xlsx
  json_schema/core/file/file_core.json
  json_schema/module/biomaterial/death.json
  json_schema/module/ontology/file_content_ontology.json
  json_schema/module/ontology/file_format_ontology.json
  json_schema/module/project/contact.json
  json_schema/module/protocol/channel.json
  json_schema/system/provenance.json
  json_schema/type/biomaterial/donor_organism.json
  json_schema/type/biomaterial/organoid.json
  json_schema/type/protocol/biomaterial_collection/ipsc_induction_protocol.json
  json_schema/type/protocol/imaging/imaging_protocol.json
  json_schema/type/protocol/sequencing/sequencing_protocol.json
  json_schema/versions.json
  src/human_readable_json.py
  src/schema_linter.py
  tests/schema_test_files/process/test_pass_analysis_process.json
Labels: release

#1070 Release from integration to staging - 2019-07-17
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  docs/release_process.md
  json_schema/module/ontology/file_content_ontology.json
  json_schema/versions.json
Labels: release

#1071 Updated src/ readme and commented some of the metadata scripts
  src/README.md
  src/human_readable_json.py
  src/release_prepare.py
  src/version_update.py
Labels: documentation

#1066 Added full stop to description of 24 schemas. Fixes #1035
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/module/ontology/biological_macromolecule_ontology.json
  json_schema/module/ontology/cell_cycle_ontology.json
  json_schema/module/ontology/cell_type_ontology.json
  json_schema/module/ontology/cellular_component_ontology.json
  json_schema/module/ontology/development_stage_ontology.json
  json_schema/module/ontology/disease_ontology.json
  json_schema/module/ontology/enrichment_ontology.json
  json_schema/module/ontology/ethnicity_ontology.json
  json_schema/module/ontology/instrument_ontology.json
  json_schema/module/ontology/length_unit_ontology.json
  json_schema/module/ontology/library_amplification_ontology.json
  json_schema/module/ontology/library_construction_ontology.json
  json_schema/module/ontology/mass_unit_ontology.json
  json_schema/module/ontology/microscopy_ontology.json
  json_schema/module/ontology/organ_part_ontology.json
  json_schema/module/ontology/process_type_ontology.json
  json_schema/module/ontology/protocol_type_ontology.json
  json_schema/module/ontology/sequencing_ontology.json
  json_schema/module/ontology/species_ontology.json
  json_schema/module/ontology/strain_ontology.json
  json_schema/module/ontology/time_unit_ontology.json
  json_schema/type/process/analysis/analysis_process.json
  json_schema/type/protocol/imaging/imaging_preparation_protocol.json
  json_schema/type/protocol/imaging/imaging_protocol.json
  json_schema/versions.json
Labels: content

#1055 Added Security SOP document. Fixes #1049
  docs/snyk_security_updates.md
Labels: documentation

#1062 Snyk fix bbf538e61bbff18dfca288a8280ffa40
  tests/.snyk
  tests/package-lock.json
  tests/package.json
Labels: Security

#1082 [Snyk] Fix for 1 vulnerable dependencies
  tests/.snyk
  tests/package-lock.json
  tests/package.json
Labels: Security

#1077 Adding two new fields representing the major and minor version of the schema in each of the type metadata schemas. Fixes #1076.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/system/provenance.json
  json_schema/versions.json
Labels: content
