Repository HumanCellAtlas/metadata-schema, pull requests merged in 2019-02, with the labels that each got.

#790 Release from develop to integration 2019-02-01
  changelog.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  docs/release_process.md
  json_schema/module/ontology/biological_macromolecule_ontology.json
  json_schema/module/ontology/cell_cycle_ontology.json
  json_schema/module/ontology/cell_type_ontology.json
  json_schema/module/ontology/cellular_component_ontology.json
  json_schema/module/ontology/development_stage_ontology.json
  json_schema/module/ontology/disease_ontology.json
  json_schema/module/ontology/enrichment_ontology.json
  json_schema/module/ontology/ethnicity_ontology.json
  json_schema/module/ontology/instrument_ontology.json
  json_schema/module/ontology/length_unit_ontology.json
  json_schema/module/ontology/library_amplification_ontology.json
  json_schema/module/ontology/library_construction_ontology.json
  json_schema/module/ontology/mass_unit_ontology.json
  json_schema/module/ontology/microscopy_ontology.json
  json_schema/module/ontology/organ_ontology.json
  json_schema/module/ontology/organ_part_ontology.json
  json_schema/module/ontology/process_type_ontology.json
  json_schema/module/ontology/protocol_type_ontology.json
  json_schema/module/ontology/sequencing_ontology.json
  json_schema/module/ontology/species_ontology.json
  json_schema/module/ontology/strain_ontology.json
  json_schema/module/ontology/time_unit_ontology.json
  json_schema/module/process/sequencing/plate_based_sequencing.json
  json_schema/module/protocol/channel.json
  json_schema/module/protocol/target.json
  json_schema/type/biomaterial/cell_line.json
  json_schema/type/biomaterial/cell_suspension.json
  json_schema/type/biomaterial/donor_organism.json
  json_schema/type/biomaterial/imaged_specimen.json
  json_schema/type/biomaterial/organoid.json
  json_schema/type/file/analysis_file.json
  json_schema/type/file/image_file.json
  json_schema/type/file/reference_file.json
  json_schema/type/file/supplementary_file.json
  json_schema/type/project/project.json
  json_schema/type/protocol/biomaterial_collection/aggregate_generation_protocol.json
  json_schema/type/protocol/imaging/imaging_protocol.json
  json_schema/type/protocol/protocol.json
  json_schema/type/protocol/sequencing/sequencing_protocol.json
  json_schema/versions.json
  src/release_prepare.py
  src/schema_linter.py
Labels: release

#753 Change total_cell_count to estimated_cell_count. Fixes #649.
  changelog.md
  docs/jsonBrowser/type.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
  json_schema/type/biomaterial/cell_suspension.json
  json_schema/versions.json
Labels: content

#795 Release from develop to integration - 2019-02-05
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
  json_schema/core/biomaterial/biomaterial_core.json
  json_schema/module/ontology/disease_ontology.json
  json_schema/module/process/sequencing/barcode.json
  json_schema/module/process/sequencing/plate_based_sequencing.json
  json_schema/system/links.json
  json_schema/type/biomaterial/cell_suspension.json
  json_schema/versions.json
Labels: release

#803 Imaging preparation protocol patch updates. Fixes Issue#796.
  changelog.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/protocol/imaging/imaging_preparation_protocol.json
  json_schema/versions.json
Labels: content

#819 Hancestro update example to include colon Fixes #818
  changelog.md
  docs/jsonBrowser/module.md
  json_schema/module/ontology/ethnicity_ontology.json
  json_schema/versions.json
Labels: bug

#817 Some patch changes caught by linter. Fixes #816.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/module/biomaterial/medical_history.json
  json_schema/module/protocol/channel.json
  json_schema/module/protocol/target.json
  json_schema/versions.json
Labels: content

#811 Release from staging to production - 2019-02-12
  .github/pull_request_template.md
  changelog.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
  infrastructure_testing_files/current/dcp_scale_test_metadata_1000_glioblastoma_cells.xlsx
  infrastructure_testing_files/current/dcp_scale_test_metadata_100_glioblastoma_cells.xlsx
  infrastructure_testing_files/current/dcp_scale_test_metadata_200_glioblastoma_cells.xlsx
  infrastructure_testing_files/current/dcp_scale_test_metadata_32_10x.xlsx
  infrastructure_testing_files/current/dcp_scale_test_metadata_400_glioblastoma_cells.xlsx
  infrastructure_testing_files/current/dcp_scale_test_pancreas6decades.xlsx
  json_schema/module/biomaterial/preservation_storage.json
  json_schema/module/project/funder.json
  json_schema/type/project/project.json
  json_schema/versions.json
  src/README.md
  src/human_readable_json.py
  src/json_examples_validate_against_schema.py
  src/json_fields_to_csv.py
  src/json_to_spreadsheet_template.py
  src/ref_updater.py
  src/schema_test_suite.py
  src/schemas_are_valid_json.py
  tests/schema_test_files/README.md
  tests/schema_test_files/project/test_fail_project_0.json
  tests/schema_test_files/project/test_pass_project_0.json
Labels: release

#815 Update release process SOP
  docs/release_process.md
Labels: documentation

#804 Committer document updates for PR review process. Fixes #800.
  .github/pull_request_template.md
  docs/committers.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
Labels: documentation

#820 Release from integration to staging - 2019-02-13
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  docs/release_process.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
  json_schema/core/biomaterial/biomaterial_core.json
  json_schema/module/ontology/biological_macromolecule_ontology.json
  json_schema/module/ontology/cell_cycle_ontology.json
  json_schema/module/ontology/cell_type_ontology.json
  json_schema/module/ontology/cellular_component_ontology.json
  json_schema/module/ontology/development_stage_ontology.json
  json_schema/module/ontology/disease_ontology.json
  json_schema/module/ontology/enrichment_ontology.json
  json_schema/module/ontology/ethnicity_ontology.json
  json_schema/module/ontology/instrument_ontology.json
  json_schema/module/ontology/length_unit_ontology.json
  json_schema/module/ontology/library_amplification_ontology.json
  json_schema/module/ontology/library_construction_ontology.json
  json_schema/module/ontology/mass_unit_ontology.json
  json_schema/module/ontology/microscopy_ontology.json
  json_schema/module/ontology/organ_ontology.json
  json_schema/module/ontology/organ_part_ontology.json
  json_schema/module/ontology/process_type_ontology.json
  json_schema/module/ontology/protocol_type_ontology.json
  json_schema/module/ontology/sequencing_ontology.json
  json_schema/module/ontology/species_ontology.json
  json_schema/module/ontology/strain_ontology.json
  json_schema/module/ontology/time_unit_ontology.json
  json_schema/module/process/sequencing/barcode.json
  json_schema/module/process/sequencing/plate_based_sequencing.json
  json_schema/module/protocol/channel.json
  json_schema/module/protocol/target.json
  json_schema/system/links.json
  json_schema/type/biomaterial/cell_line.json
  json_schema/type/biomaterial/cell_suspension.json
  json_schema/type/biomaterial/donor_organism.json
  json_schema/type/biomaterial/imaged_specimen.json
  json_schema/type/biomaterial/organoid.json
  json_schema/type/file/analysis_file.json
  json_schema/type/file/image_file.json
  json_schema/type/file/reference_file.json
  json_schema/type/file/supplementary_file.json
  json_schema/type/project/project.json
  json_schema/type/protocol/biomaterial_collection/aggregate_generation_protocol.json
  json_schema/type/protocol/imaging/imaging_protocol.json
  json_schema/type/protocol/protocol.json
  json_schema/type/protocol/sequencing/sequencing_protocol.json
  json_schema/versions.json
  src/release_prepare.py
  src/schema_linter.py
Labels: release

#822 Changed date established format to date. Fixes #821.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/biomaterial/cell_line.json
  json_schema/versions.json
Labels: content

#806 Make insdc_run plural. Fixes #805.
  changelog.md
  docs/jsonBrowser/type.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
  json_schema/type/file/sequence_file.json
  json_schema/versions.json
Labels: content

#825 Updated 10x spreadsheet to match new pipelines query.
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
Labels: documentation

#827 Release from staging to production - 2019-02-20
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  docs/release_process.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
  json_schema/core/biomaterial/biomaterial_core.json
  json_schema/module/ontology/biological_macromolecule_ontology.json
  json_schema/module/ontology/cell_cycle_ontology.json
  json_schema/module/ontology/cell_type_ontology.json
  json_schema/module/ontology/cellular_component_ontology.json
  json_schema/module/ontology/development_stage_ontology.json
  json_schema/module/ontology/disease_ontology.json
  json_schema/module/ontology/enrichment_ontology.json
  json_schema/module/ontology/ethnicity_ontology.json
  json_schema/module/ontology/instrument_ontology.json
  json_schema/module/ontology/length_unit_ontology.json
  json_schema/module/ontology/library_amplification_ontology.json
  json_schema/module/ontology/library_construction_ontology.json
  json_schema/module/ontology/mass_unit_ontology.json
  json_schema/module/ontology/microscopy_ontology.json
  json_schema/module/ontology/organ_ontology.json
  json_schema/module/ontology/organ_part_ontology.json
  json_schema/module/ontology/process_type_ontology.json
  json_schema/module/ontology/protocol_type_ontology.json
  json_schema/module/ontology/sequencing_ontology.json
  json_schema/module/ontology/species_ontology.json
  json_schema/module/ontology/strain_ontology.json
  json_schema/module/ontology/time_unit_ontology.json
  json_schema/module/process/sequencing/barcode.json
  json_schema/module/process/sequencing/plate_based_sequencing.json
  json_schema/module/protocol/channel.json
  json_schema/module/protocol/target.json
  json_schema/system/links.json
  json_schema/type/biomaterial/cell_line.json
  json_schema/type/biomaterial/cell_suspension.json
  json_schema/type/biomaterial/donor_organism.json
  json_schema/type/biomaterial/imaged_specimen.json
  json_schema/type/biomaterial/organoid.json
  json_schema/type/file/analysis_file.json
  json_schema/type/file/image_file.json
  json_schema/type/file/reference_file.json
  json_schema/type/file/supplementary_file.json
  json_schema/type/project/project.json
  json_schema/type/protocol/biomaterial_collection/aggregate_generation_protocol.json
  json_schema/type/protocol/imaging/imaging_protocol.json
  json_schema/type/protocol/protocol.json
  json_schema/type/protocol/sequencing/sequencing_protocol.json
  json_schema/versions.json
  src/release_prepare.py
  src/schema_linter.py
Labels: release

#832 Add enum value to preservation_method. Fixes #831.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/module/biomaterial/preservation_storage.json
  json_schema/versions.json
Labels: content

#834 Target patch updates. Fixes #830.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/module/protocol/target.json
  json_schema/versions.json
Labels: content

#793 Fix state_of_specimen array fields to be plural. Fixes #792.
  changelog.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  json_schema/module/biomaterial/state_of_specimen.json
  json_schema/versions.json
Labels: content

#850 Add administrator value to project role enum. Fixes #845.
  changelog.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  json_schema/module/project/contact.json
  json_schema/versions.json
Labels: content

#833 New property migrations json file
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/property_migrations.json
  json_schema/sample_property_migrations.json
  src/json_doc_migrations.py
  src/migration_test_donor1.json
  src/migration_test_donor2.json
  src/migration_test_specimen1.json
Labels: infrastructure

#810 Updated process module fields. Fixes #809.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
  json_schema/module/process/sequencing/insdc_experiment.json
  json_schema/module/process/sequencing/plate_based_sequencing.json
  json_schema/versions.json
Labels: content
