Repository HumanCellAtlas/metadata-schema, pull requests merged in 2019-01, with the labels that each got.

#708 ZP Project patch updates. Fixes#682.
  changelog.md
  json_schema/versions.json
Labels: bug

#684 Library preparation protocol patch updates.
  changelog.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/protocol/sequencing/library_preparation_protocol.json
  json_schema/versions.json
Labels: content

#702 Funder and publication patch updates.
  changelog.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  json_schema/module/project/funder.json
  json_schema/module/project/publication.json
  json_schema/versions.json
Labels: content

#694 Analysis protocol patch updates.
  changelog.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/protocol/analysis/analysis_protocol.json
  json_schema/versions.json
Labels: content

#681 Supplementary file patch updates.
  changelog.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/file/supplementary_file.json
  json_schema/versions.json
Labels: content

#695 Analysis process patch updates.
  changelog.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/process/analysis/analysis_process.json
  json_schema/versions.json
Labels: content

#707 Patch updates to the imaging_protocol.json schema to adhere to the Style Guide. Fixes#706
  changelog.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/protocol/imaging/imaging_protocol.json
  json_schema/versions.json
Labels: content

#693 Reference file patch updates.
  changelog.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/file/reference_file.json
  json_schema/versions.json
Labels: content

#704 Core schema patch updates.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/core/biomaterial/biomaterial_core.json
  json_schema/core/file/file_core.json
  json_schema/core/process/process_core.json
  json_schema/core/project/project_core.json
  json_schema/core/protocol/protocol_core.json
  json_schema/versions.json
Labels: content

#692 Biomaterial modules patch updates.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/module/biomaterial/cell_morphology.json
  json_schema/module/biomaterial/death.json
  json_schema/module/biomaterial/familial_relationship.json
  json_schema/module/biomaterial/growth_conditions.json
  json_schema/module/biomaterial/human_specific.json
  json_schema/module/biomaterial/medical_history.json
  json_schema/module/biomaterial/mouse_specific.json
  json_schema/module/biomaterial/preservation_storage.json
  json_schema/module/biomaterial/state_of_specimen.json
  json_schema/versions.json
Labels: content

#730 Update release_process.md documentation. Fixes Issue #713.
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  docs/release_process.md
Labels: documentation

#737 Release from develop to integration 2019-01-15
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  docs/release_process.md
  json_schema/core/project/project_core.json
  json_schema/module/process/sequencing/10x.json
  json_schema/type/biomaterial/donor_organism.json
  json_schema/type/biomaterial/organoid.json
  json_schema/type/protocol/sequencing/sequencing_protocol.json
  json_schema/versions.json
Labels: release

#655 Organoid field name (major) changes. Fixes #480.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/biomaterial/organoid.json
  json_schema/versions.json
Labels: content

#744 Update funder-related fields to be required.
  changelog.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/type.md
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
  infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
  json_schema/module/project/funder.json
  json_schema/type/project/project.json
  json_schema/versions.json
  tests/schema_test_files/project/test_fail_project_0.json
  tests/schema_test_files/project/test_pass_project_0.json
Labels: content

#751 Remove commas from storage_method enum list. Fixes #743.
  changelog.md
  docs/jsonBrowser/module.md
  json_schema/module/biomaterial/preservation_storage.json
  json_schema/versions.json
Labels: content

#766 Release from integration to staging 2019-01-23
  .github/ISSUE_TEMPLATE/schema_update.md
  changelog.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  docs/release_process.md
  json_schema/module/biomaterial/timecourse.json
  json_schema/type/biomaterial/organoid.json
  json_schema/versions.json
  tests/package-lock.json
  tests/package.json
Labels: release

#748 Change aggregate_generation_protocol to adhere to Style Guide. Fixes #746.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/protocol/biomaterial_collection/aggregate_generation_protocol.json
  json_schema/versions.json
Labels: content

#761 Remove organoid_type field. Fixes #736.
  changelog.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/biomaterial/organoid.json
  json_schema/versions.json
Labels: content

#764 Add required model_organ to cell line. Fixes #606.
  changelog.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/biomaterial/cell_line.json
  json_schema/versions.json
Labels: content

#763 Change project accessions. Fixes #324.
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/type/project/project.json
  json_schema/versions.json
Labels: content

#769 Change familial_relationship to be plural (array). Fixes #768.
  changelog.md
  docs/jsonBrowser/type.md
  json_schema/type/biomaterial/donor_organism.json
  json_schema/versions.json
Labels: content
