Repository HumanCellAtlas/metadata-schema, pull requests merged in 2020-06, with the labels that each got.

#1286 Changed reference_bundle to files and removed input_bundles. Fixes #1275 and #1290
  changelog.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/property_migrations.json
  json_schema/type/process/analysis/analysis_process.json
  json_schema/versions.json
  tests/schema_test_files/process/test_pass_analysis_process.json
  tests/schema_test_files/process/test_pass_new_analysis_process.json
Labels: content, hotfix

#1291 [STAGING] Changed reference_bundle to files and removed input_bundles. Fixes #1275 and #1290
  changelog.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/property_migrations.json
  json_schema/type/process/analysis/analysis_process.json
  json_schema/versions.json
  tests/schema_test_files/process/test_pass_analysis_process.json
  tests/schema_test_files/process/test_pass_new_analysis_process.json
Labels: content, hotfix

#1292 [INTEGRATION] - Changed reference_bundle to files and removed input_bundles. Fixes #1275 and #1290
  changelog.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/property_migrations.json
  json_schema/type/process/analysis/analysis_process.json
  json_schema/versions.json
  tests/schema_test_files/process/test_pass_analysis_process.json
  tests/schema_test_files/process/test_pass_new_analysis_process.json
Labels: content, hotfix

#1293 [DEV] - Changed reference_bundle to files and removed input_bundles. Fixes #1275 and #1290
  changelog.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/property_migrations.json
  json_schema/type/process/analysis/analysis_process.json
  json_schema/versions.json
  tests/schema_test_files/process/test_pass_analysis_process.json
  tests/schema_test_files/process/test_pass_new_analysis_process.json
Labels: content, hotfix

#1284 Made changes to links.json schema. Fixes #1285
  changelog.md
  json_schema/system/links.json
  json_schema/type/process/analysis/analysis_process.json
  json_schema/update_log.csv
  json_schema/versions.json
  tests/schema.test.js
  tests/schema_test_files/system/test_pass_links.json
Labels: content, help wanted, hotfix

#1295 [STAGING] - Made changes to links.json schema. Fixes #1285
  changelog.md
  json_schema/system/links.json
  json_schema/type/process/analysis/analysis_process.json
  json_schema/update_log.csv
  json_schema/versions.json
  tests/schema.test.js
  tests/schema_test_files/system/test_pass_links.json
Labels: content, hotfix

#1296 [INTEGRATION] - Made changes to links.json schema. Fixes #1285
  changelog.md
  json_schema/system/links.json
  json_schema/type/process/analysis/analysis_process.json
  json_schema/update_log.csv
  json_schema/versions.json
  tests/schema.test.js
  tests/schema_test_files/system/test_pass_links.json
Labels: content, hotfix

#1297 [DEV] - Made changes to links.json schema. Fixes #1285
  changelog.md
  json_schema/system/links.json
  json_schema/type/process/analysis/analysis_process.json
  json_schema/update_log.csv
  json_schema/versions.json
  tests/schema.test.js
  tests/schema_test_files/system/test_pass_links.json
Labels: content, hotfix

#1299 Added hotfix section. Fixes #1298.
  docs/release_process.md
Labels: documentation, hotfix

#1304 Esv release hotfix issue1298
  docs/release_process.md
Labels: documentation, hotfix

#1305 Esv release hotfix issue1298
  docs/release_process.md
Labels: documentation, hotfix

#1306 Esv release hotfix issue1298
  docs/release_process.md
Labels: documentation, hotfix

#1307 Fix links.json refs Fixes #1303
  changelog.md
  json_schema/system/links.json
  json_schema/update_log.csv
  json_schema/versions.json
Labels: content, hotfix

#1308 Hotfix: Fix refs links in links.json Fixes #1303
  changelog.md
  json_schema/system/links.json
  json_schema/update_log.csv
  json_schema/versions.json
Labels: content, hotfix

#1309 Hotfix: fix links in links.json fixes #1303
  changelog.md
  json_schema/system/links.json
  json_schema/update_log.csv
  json_schema/versions.json
Labels: content, hotfix

#1310 Hotfix: fix links in links.json fixes #1303
  changelog.md
  json_schema/system/links.json
  json_schema/update_log.csv
  json_schema/versions.json
Labels: content, hotfix

#1311 manually updated changelog for links hotfix
  changelog.md
Labels: hotfix

#1312 Hotfix: Add file descriptor schema. Fixes #1289
  changelog.md
  json_schema/system/file_descriptor.json
  json_schema/versions.json
Labels: content, hotfix

#1313 Hotfix: add file_descriptor.json
  changelog.md
  json_schema/system/file_descriptor.json
  json_schema/versions.json
Labels: content, hotfix

#1314 Hotfix: Add file_descriptor.json
  changelog.md
  json_schema/system/file_descriptor.json
  json_schema/versions.json
Labels: content, hotfix

#1315 Hotfix: Add file_descriptor.json
  changelog.md
  json_schema/system/file_descriptor.json
  json_schema/versions.json
Labels: content, hotfix

#1319 Remove major/minor version fields from file_descriptor & provenance. Fixes #1317
  changelog.md
  json_schema/property_migrations.json
  json_schema/system/file_descriptor.json
  json_schema/versions.json
Labels: content, hotfix

#1321 Remove major/minor version fields from file_descriptor Fixes #1317
  changelog.md
  json_schema/property_migrations.json
  json_schema/system/file_descriptor.json
  json_schema/versions.json
Labels: content, hotfix

#1322 Remove major/minor version fields from file_descriptor Fixes #1317
  changelog.md
  json_schema/property_migrations.json
  json_schema/system/file_descriptor.json
  json_schema/versions.json
Labels: content, hotfix

#1323 Remove major/minor version fields from file_descriptor Fixes #1317
  changelog.md
  json_schema/property_migrations.json
  json_schema/system/file_descriptor.json
  json_schema/versions.json
Labels: content, hotfix
