Repository HumanCellAtlas/metadata-schema, pull requests merged in 2021-03, with the labels that each got.

#1369 Release from develop to staging - 2021-03-16
  .pullapprove.yml
  changelog.md
  docs/jsonBrowser/type.md
  infrastructure_testing_files/README.md
  infrastructure_testing_files/test_metadata_hca_spreadsheet.xlsx
  infrastructure_testing_files/test_metadata_hca_spreadsheet_imaging.xlsx
  json_schema/system/links.json
  json_schema/type/project/project.json
  json_schema/versions.json
  src/schema_linter.py
  tests/package-lock.json
  tests/schema.test.js
  tests/schema_test_files/system/test_fail_links.json
Labels: release

#1361 Add estimated cell count to project.json. Fixes #1343
  changelog.md
  docs/jsonBrowser/type.md
  json_schema/type/project/project.json
  src/release_prepare.py
Labels: content

#1373 Enable ability to assign ontologised Data Use Restriction at the project level. Fixes #1342
  changelog.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/module/ontology/data_use_ontology.json
  json_schema/type/project/project.json
  json_schema/versions.json
  tests/schema_test_files/project/test_pass_project_0.json
Labels: content, project

#1375 Enable ability to assign ontologised Data Use Restriction at the project level. Fixes #1342
  changelog.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/module/ontology/data_use_ontology.json
  json_schema/type/project/project.json
  json_schema/versions.json
  src/release_prepare.py
  tests/schema_test_files/project/test_pass_project_0.json
Labels: content

#1365 Edit pullapprove config
  .pullapprove.yml
Labels: content

#1374 Enhance metadata capture describing matrices. Fixes #1372
  changelog.md
  docs/jsonBrowser/core.md
  docs/jsonBrowser/module.md
  docs/jsonBrowser/required_fields.md
  docs/jsonBrowser/type.md
  json_schema/core/file/file_core.json
  json_schema/module/protocol/matrix.json
  json_schema/type/file/analysis_file.json
  json_schema/type/protocol/analysis/analysis_protocol.json
  json_schema/versions.json
Labels: content

#1377 Roll back data_use_restrictions field in project schema
  changelog.md
  docs/jsonBrowser/type.md
  json_schema/property_migrations.json
  json_schema/type/project/project.json
  json_schema/versions.json
  tests/schema_test_files/project/test_pass_project_0.json
Labels: content
